import type { PlanEngine, PlanParams, WeekTemplate, WeekContext } from './types';

export const aiCoach: PlanEngine = {
  dojo: 'ai-coach',
  displayName: 'AI Coach',
  philosophy:
    'A personalized plan generated by your AI coach based on your fitness assessment, race goal, and training history. Adapts as you progress.',
  defaultProgramWeeks: 16,
  defaultLongRunCapKm: 35,
  status: 'full',
  entryWeeklyLoadKm: () => 40,
  calendarConfig: {
    taper: {
      schedule: [
        { withinDays: 14, factor: 0.7 },
        { withinDays: 7, factor: 0.5 },
      ],
      raceWeekStyle: 'two-day-rest',
    },
    volumeScale: { reducedFactor: 0.6, travelOnlyFactor: 0.4, noTrainingZeroesOut: true },
    tuneups: { enabled: true, taperDays: 3, recoveryDays: 4 },
    honourRecurringSessions: true,
    annotateNinjaLoops: true,
  },
  derivePaceZones: () => ({
    recovery:   { minSpk: 390, maxSpk: 450 },
    easy:       { minSpk: 330, maxSpk: 390 },
    long:       { minSpk: 330, maxSpk: 390 },
    marathon:   { minSpk: 270, maxSpk: 300 },
    threshold:  { minSpk: 240, maxSpk: 270 },
    interval:   { minSpk: 210, maxSpk: 240 },
    repetition: { minSpk: 180, maxSpk: 210 },
  }),
  renderWeek(_params: PlanParams, weekNumber: number, _context?: WeekContext): WeekTemplate {
    // AI Coach sessions come from the ai_plan_sessions DB table, not from this method.
    // Callers that need real data (snapshot-builder, CalendarPage) query the DB directly.
    // This stub satisfies the PlanEngine interface for UI registration purposes.
    return {
      weekNumber,
      phaseName: 'AI Coached',
      totalKmTarget: 0,
      longRunKmTarget: 0,
      days: [],
    };
  },
};
